### PR TITLE
Emergency services

### PR DESCRIPTION
**Pull request by wareid**
Making some amendments to the suggested change from PR #141

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/143.html" title="Last updated on Jun 30, 2020, 2:41 PM UTC (4e2b851)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/143/b0398dc...4e2b851.html" title="Last updated on Jun 30, 2020, 2:41 PM UTC (4e2b851)">Diff</a>

### CODE REVIEW

**Comment by nigelmegitt** [comment]
I prefer #141 to this alternative proposal. The term "emergency services" already might include law enforcement or might not, and gives adequate flexibility, without making the further tweaks proposed here.

**Comment by TzviyaSiegman** [comment]
Thanks @nigelmegitt. We agreed to this at today's meeting (minutes https://www.w3.org/2020/06/30-pwe-minutes.html]). Please review the minutes for our discussion about why we are including both phrases.

**Comment by nigelmegitt** [comment]
@TzviyaSiegman indeed I did review the minutes before adding my "request changes review" and sent a note to the reflector explaining this position, archived at https://lists.w3.org/Archives/Public/public-pwe/2020Jun/0013.html

**Comment by cwilso** [comment]
I would +1 Nigel's comments (both the short one above, and the longer version in archive).  I do not think removing "law enforcement" in favor of just "emergency services" weakens the text, but I do think it would make some potential users of this text more comfortable.

**Comment by TzviyaSiegman** [comment]
Closing in favor of #141

**Pull request closed without merging**
