### PR TITLE
Adjustment to Patronizing language section

### PR DESCRIPTION
**Pull request by TzviyaSiegman**
* Edited based on discussion in #45. 
* Please restrict comments to editorial feedback.

### CODE REVIEW

**Comment by TzviyaSiegman** [comment]
After discussing this issue with those more experienced with writing CoCs, I think we should close the PR without merging. There are several reasons:

We could adopt the approach that "If what you’re doing is making someone feel uncomfortable, that counts as harassment and is enough reason to stop doing it" (I strongly recommend considering this approach before responding to this comment.)

We have discussed in meetings that getting into explanations and longer descriptions within CoC docs runs into two major risks: 
1. The likelihood of the whole CoC being read thoroughly is lessened
2. The more specific wording will be used to excuse away bad behavior or justify the use of certain phrases as “acceptable”

**Comment by vlevantovsky** [comment]
@TzviyaSiegman - working backwards through the list of points you made in the last  comment:

> The more specific wording will be used to excuse away bad behavior or justify the use of certain phrases as “acceptable”
This is exactly the issue we are trying to correct. Saying that "Pedantic or repeated corrections that don't contribute to the conversation" is an unacceptable behavior makes it clear and unambiguous, appending (For example ...) to it only weakens the point we are trying to make, and gives an excuse to bad behavior - I can almost here someone making an excuse "I didn't use the "for example, ..." words, therefore the corrections I made are not pedantic". Since it is not possible to mention all offensive / trigger words as examples - we'd be better off not mentioning them at all.

> longer descriptions within CoC docs runs into major risks [where t]he likelihood of the whole CoC being read thoroughly is lessened
I'd say that we are already deep into the woods of the CoC being too verbose. This is exactly the reason the old PWETF draft made an attempt to keep the CoC as concise and to the point as possible, comprised of only four major points that defined unacceptable behavior:

- W3C community participants should treat each other with respect and professionalism and be mindful of cultural differences.
- W3C community participants should communicate constructively and avoid insulting, unwelcome or demeaning behavior.
- W3C strictly prohibits discrimination, intimidation, harassment, and bullying of any kind and on any basis.
- W3C will not tolerate abusive behavior in any form, whether it is verbal, physical, sexual, or implied.

I do believe that these four statements cover all major issues we are trying to address, and leave absolutely no room for interpretation by bad actors - this is the wording that has a highest likelihood it will be read thoroughly. So, if (after privately discussing the issues with someone outside this group) you unilaterally decide that this PR should be closed without merging, we should probably reverse all changes and start with the concise list of four bullet point made in the old PWETF draft, and see if there is anything missing there that needs to be extended or elaborated.
Alternatively, we may also wish to consult the [WHATWG Code of Conduct](https://whatwg.org/code-of-conduct) as a reference.

**Comment by wareid** [comment]
The phrasing including the more specific wording is the best option (no need to close, just amend it a little to include Nigel's phrasing). Including the example, as an example, is helpful for people who are unsure of how someone else might take that phrase, but "well, actually" is definitely not the only way for someone to speak patronizingly to another.

Thanks @vlevantovsky for providing another example of a CoC for us to look at, maybe we should do more research into others that we like/dislike! I personally don't think WHATWG's goes into enough detail on it's own, but it also references the much more comprehensive http://citizencodeofconduct.org which I think makes up for the lack of detail. I don't believe we should do the same though. We have to remember with people coming from many backgrounds/countries that we have to be clear. We can balance the issue of being too verbose by providing examples or definitions later in the document while keeping the main sections quite concise. Bolstering the glossary would definitely be one way to do it. We have to keep in mind that we, as people who read CoC's and are discussing them frequently, know what "discrimination" or "harassment" mean in this context, but if you're not thinking about these things all of the time, you might fall back on the social or legal norms you are familiar with, which is reasonable if no clear definition is provided! 

The previous draft from the PWETF is a great document to work from. I don't have the full history as I'm a newer member, but it's apparent to me that we should use it just as much as we have referenced other CoCs we like. As it was not adopted, I take that to mean it did not have everything that was needed, and the activities here will hopefully build on that foundation to create something even better. I find it really derailing to the conversation that every time we have any sort of back and forth on a topic, the draft is brought up as the solution. I can understand us using certain bits of phrasing or ideas, but whole sections when we've already agreed on a majority of the content seems aimed to disrupt.

As a group that is focused on creating a Positive Work Environment, this particular action doesn't feel particularly positive or productive, but this is a personal opinion and I understand if not everyone agrees.

**Comment by TzviyaSiegman** [comment]
This will be managed by @AdaRoseCannon. I don't seem to be able to assign the issue to her though.

**Comment by AdaRoseCannon** [comment]
I may need to be added as a contributor to the w3c Github organisation.

**Comment by TzviyaSiegman** [comment]
@swickr please add @AdaRoseCannon to this repo

**Comment by AdaRoseCannon** [comment]
Merging as is.

**Pull request merged**
