### PR TITLE
added rapid response info to Reporting

### PR DESCRIPTION
**Pull request by TzviyaSiegman**
based on discussion with @swickr and @wseltzer

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/51.html" title="Last updated on Aug 8, 2019, 2:57 PM UTC (78f422c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/51/46f156a...78f422c.html" title="Last updated on Aug 8, 2019, 2:57 PM UTC (78f422c)">Diff</a>

### CODE REVIEW

**Comment by TzviyaSiegman** [comment]
ping @swickr - any update?

**Comment by AdaRoseCannon** [comment]
From the call suggest ombuds@w3.org for the @@@

**Comment by AdaRoseCannon** [comment]
I added the ombuds email and the suggestion to contact building staff for assistance contacting law enforcement.

I will base the next PR for reporting onto this one.

**Comment by jorydotcom** [comment]
Thank you @AdaRoseCannon !

**Pull request merged**
