### PR TITLE
Start editing glossary

### PR DESCRIPTION
**Pull request by AdaRoseCannon**
This PR is to address is #62

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/66.html" title="Last updated on Dec 18, 2019, 8:37 PM UTC (5f436d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/66/5cc109d...5f436d8.html" title="Last updated on Dec 18, 2019, 8:37 PM UTC (5f436d8)">Diff</a>

### CODE REVIEW

**Comment by TzviyaSiegman** [comment]
@AdaRoseCannon and I defined many terms. The following still need definition:

- Enforcers of this Code (poss "see ombuds")
- Inclusivity (especially in context)
- Neurotypical
- Ombudsperson
- Professionalism (let's avoid making professionalism synonymous with euro-centric politeness)
- Sexism

We recommend not defining the following terms because they do not require context and are part of common parlance. We plan to translate the CEPC into many languages, so English as a Second Language should not be an issue:

- Abusive Behavior (well defined in the document)
- Constructive communication
- Disability
- Ethnicity
- Intimidating
- Patronizing language/behavior (defined in the doc)
- Personal behavior
- physical appearance
cc @jorydotcom @wareid

**Comment by wareid** [comment]
Meant to comment on friday! This change looks fine to me. Do we have any recommended sources for filling in the missing definitions? I would be loathe to make something up on the fly if better prior work has been done.

**Comment by TzviyaSiegman** [comment]
We intend to publish with a relatively limited glossary and ask people to open issues if additional terms are required.

**Comment by BarbaraHochgesang** [comment]
Suggest adding.  
Microaggressions - Defined as brief and common daily verbal, behavioral, and environmental communications, whether intentional or unintentional, that transmit hostile, derogatory, or negative messages to a target person because they belong to a stigmatized group.

**Comment by TzviyaSiegman** [comment]
Thanks @BarbaraHochgesang. Are your proposing a minor edit to the existing language?

> Microaggression is a term used for brief and commonplace daily verbal, behavioural, or environmental indignities, whether intentional or unintentional, that communicate hostile, derogatory, or negative prejudicial slights and insults toward any group, particularly culturally marginalized group. 

The differences are in the terms "prejudicial" and "stigmatized" vs "marginalized"

**Comment by BarbaraHochgesang** [comment]
That could be a call by the group.  The term "marginalized" casts a broader net.  A person, group, or concept treated as insignificant or peripheral for whatever reason.
Barbara Hochgesang

**Comment by brewerj** [comment]
+1 to adding a definition of microaggression
-1 to adding a definition of professionalism. Across the broad range of cultures represented at W3C, I am skeptical that we can define this in a generalized way.

**Comment by TzviyaSiegman** [comment]
agreed to s/stigmatized/marginalized

**Comment by TzviyaSiegman** [comment]
Agreed to exclude "professionalism"

**Comment by AdaRoseCannon** [comment]
```Sexism: (Adapted from Meriam Webster) prejudice or discrimination based on perceived sex, towards groups underrepresented within the W3C namely women and non-binary people.```

**Comment by nigelmegitt** [comment]
> `Sexism: (Adapted from Meriam Webster) prejudice or discrimination based on perceived sex, towards groups underrepresented within the W3C namely women and non-binary people.`

I suggest splitting this at the comma. Sexism is prejudice or discrimination based on perceived sex, fullstop. Separately we should be clear that one of the goals of the CEPC is to ensure that all groups underrepresented or marginalised within W3C are treated properly - this is a blanket statement that covers sexism, racism, ablism etc. and is not specific to sexism. It would go without saying (here in this issue thread) that the wider context is that W3C aims for all to feel welcome to contribute and be treated with respect, and for participants to be representative of the general population, but that is probably worth being clear about if we are not already in the CEPC.

**Comment by AdaRoseCannon** [comment]
> I suggest splitting this at the comma. Sexism is prejudice or discrimination based on perceived sex, fullstop.

Nigel in the context of this work that statement is incorrect. One of the axioms upon which this code of conduct is written is that discrimination works down a power differential. 

Racism, sexism, homophobia, cissexism all work down this way. This prevents claims of revers-isms against groups aimed to support underrepresented or marginalised communities.

**Comment by nigelmegitt** [comment]
> in the context of this work that statement is incorrect

@AdaRoseCannon okay for context let's look at the proposal here for racism:

>  Racism
>
>    Racial prejudice refers to a set of discriminatory or derogatory attitudes based on assumptions deriving from perceptions about race, culture, religion and/or skin colour.
>
>    Racism is where racial prejudices work to enhance existing power imbalances in communities to further marginalize communities based upon race. 

This does the equivalent of splitting the sexism definition at the comma. I think this is a good pattern and we should do the same thing here. I don't understand why you would say this is incorrect in the context of this work.

**Pull request merged**
