### PR TITLE
glossary edits

### PR DESCRIPTION
**Pull request by TzviyaSiegman**
* s/Racial Prejudice/Prejudice
* revision of definition of reverse -isms so that it does not include implementation

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/pull/122.html" title="Last updated on Mar 4, 2020, 7:32 PM UTC (3635617)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/PWETF/122/27e4e2d...3635617.html" title="Last updated on Mar 4, 2020, 7:32 PM UTC (3635617)">Diff</a>

### CODE REVIEW

**Comment by wareid** [comment]
Looks good to me, I would suggest we extend the definition for "Prejudice" from: 

>Racial prejudice refers to a set of discriminatory or derogatory attitudes based on assumptions deriving from perceptions about race, culture, religion, and/or skin colour.

to 

> Prejudice refers to a set of discriminatory or derogatory attitudes based on assumptions deriving from perceptions about race, culture, religion, skin colour, age, sexual orientation, gender, and/or gender expression. 

Just to reflect the expansion of the definition.

**Comment by AdaRoseCannon** [comment]
This reading `(reverse racism, reverse sexism, reverse homophobia, reverse transphobia/cisphobia, etc.).` legitimises reversisms and puts them on the same level as what they are reversing.

This should not be the case since reverse racism is not a thing which can exist, one can hold racial prejudice in the opposite direction to the power imbalance but to do so is not racist.

**Comment by marcoscaceres** [comment]
After doing some more reading, and hearing people's positions on this, I have to agree with @AdaRoseCannon: The reverse-isms aren't a thing.  We should remove that.

**Comment by TzviyaSiegman** [comment]
Thanks @AdaRoseCannon and @marcoscaceres. We included Reverse -isms in the glossary because it was flagged by members of PWE as a term that needed definition in context. The definition previously listed included information about enforcement, which is not great for a glossary. 

I included the phrase "referred to"  to attempt to indicate that these are not real concepts, but perhaps that is not strong enough? I listed the terms reverse racism, reverse sexism, in parentheses so that people would be able to find them in the glossary. Would it work better if it was changed to "colloquially referred to as reverse racism..., "? I am trying to come up with a way to say (in a glossary-appropriate way) that reverse-isms are another example of -isms. I would very much appreciate suggestions.

**Comment by TzviyaSiegman** [comment]
@marcoscaceres @AdaRoseCannon @wareid What do you think of this:

> While racism, sexism, homophobia and transphobia are acts which further the power imbalances against marginalized communities, acts that go in the opposite direction are colloquially referred to as reverse-isms (as in reverse racism, reverse sexism, reverse homophobia, reverse transphobia/cisphobia). These are in fact examples of prejudice or stereotypes, demonstrating that "reverse -isms" is a false concept.

**Comment by TzviyaSiegman** [comment]
@marcoscaceres @AdaRoseCannon @wareid What do you think of this:

> While racism, sexism, homophobia and transphobia are acts which further the power imbalances against marginalized communities, acts that go in the opposite direction are colloquially referred to as reverse-isms (as in reverse racism, reverse sexism, reverse homophobia, reverse transphobia/cisphobia). These are in fact examples of prejudice or stereotypes, demonstrating that "reverse -isms" is a false concept.

**Comment by TzviyaSiegman** [comment]
@marcoscaceres @AdaRoseCannon @wareid What do you think of this:

> While racism, sexism, homophobia and transphobia are acts which further the power imbalances against marginalized communities, acts that go in the opposite direction are colloquially referred to as reverse-isms (as in reverse racism, reverse sexism, reverse homophobia, reverse transphobia/cisphobia). These are in fact examples of prejudice or stereotypes, demonstrating that "reverse -isms" is a false concept.

**Comment by TzviyaSiegman** [comment]
@marcoscaceres @AdaRoseCannon @wareid What do you think of this:

> While racism, sexism, homophobia and transphobia are acts which further the power imbalances against marginalized communities, acts that go in the opposite direction are colloquially referred to as reverse-isms (as in reverse racism, reverse sexism, reverse homophobia, reverse transphobia/cisphobia). These are in fact examples of prejudice or stereotypes, demonstrating that "reverse -isms" is a false concept.

**Comment by AdaRoseCannon** [comment]
A small tweak to clarify the last sentence: 

> These are in fact examples of prejudice or stereotypes not discrimination since they do not go against the power imbalance, as such "reverse -isms" are false concepts.

**Comment by dwsinger** [comment]
(minor) suggest inserting two pairs of commas and an 'and':
>These are, in fact, examples of prejudice or stereotypes, not discrimination, since they do not go against the power imbalance, and as such "reverse -isms" are false concepts.

**Comment by frivoal** [comment]
I think this is a good a improvement, and support it.

**Comment by fantasai** [comment]
Would suggest rephrasing the first part to not implicitly define "racism" as requiring a power imbalance, and also remove "or stereotypes" to let "prejudice" stand alone, so proposed text:

> Given racism, sexism, homophobia and transphobia further the power imbalances against marginalized communities, acts that go in the opposite direction are colloquially referred to as reverse-isms (as in reverse racism, reverse sexism, reverse homophobia, reverse transphobia/cisphobia).

I'm also confused by the statement

> These are, in fact, examples of prejudice or stereotypes, not discrimination, since they do not go against the power imbalance, and as such "reverse -isms" are false concepts.

We just said XYZ are acts that go in the opposite direction of the power imbalance, and now we're saying they aren't???

**Comment by AdaRoseCannon** [comment]
@fantasai it's the difference of discrimination vs prejudice.

**Comment by dwsinger** [comment]
I think the question concerns whether we all have the same understanding over which direction "goes against" a power imbalance; this is a textual/comprehension question, not content...

**Comment by AdaRoseCannon** [comment]
Hmm how about "since they do not further the power imbalance"?

**Comment by TzviyaSiegman** [comment]
@wareid please add "disability" to the list in prejudice, and s/about/about things such as.

**Comment by TzviyaSiegman** [comment]
@wareid please change and/or to or

**Comment by TzviyaSiegman** [comment]
What about (excluding the word discrimination which is also prohibited):

> While racism, sexism, homophobia and transphobia are acts which further the power imbalances against marginalized communities, acts that go in the opposite direction are colloquially referred to as reverse-isms (as in reverse racism, reverse sexism, reverse homophobia, reverse transphobia/cisphobia). These are, in fact, examples of prejudice or stereotypes, not of these terms, since they do not further the power imbalance, and as such "reverse -isms" are false concepts.

(or the same without the clause "not of these terms"

**Comment by jeffjaffe** [comment]
> since they do not further the power imbalance, and as such "reverse -isms" are false concepts.

I find it awkward to have the explanatory "since" clause inside of a definition.

**Comment by deborahgu** [comment]
I would remove "not of these terms," because it's awkward and the antecedent is unclear, and all of the ways to clarify it would probably open up another can of worms. It's good the way it is without that clause.

**Comment by marcoscaceres** [comment]
I'd personally feel more comfortable if we dropped any mention of "reverse-isms" entirely. By being in the document, it gives the concept a false equivalence and false legitimacy.

**Comment by TzviyaSiegman** [comment]
Resolved in PWE meeting 3/3 delete definition of reverse-isms from glossary, preserve change to prejudice

**Comment by TzviyaSiegman** [comment]
per discussion in meeting on 3/2, approval of @AdaRoseCannon and AB recommendation, this is approved.

**Pull request merged**
